# ──────────────────────────────────────────────────────────────────────────────
# hosts/nixos/configuration.nix
# ──────────────────────────────────────────────────────────────────────────────
#
# TO APPLY:
#   sudo nixos-rebuild switch --flake .#cypher-nixos
#   home-manager switch --flake .#cypher_whisperer@cypher-nixos
# ──────────────────────────────────────────────────────────────────────────────

{
  cypherOsConstants,
  ...
}:
let
  stateVersion = cypherOsConstants.stateVersion;
in
{
  imports = [
    # ──────────────────────────────────────────────────────────────────────────
    # hardware-configuration.nix is auto-generated by nixos-generate-config
    # during install. It declares a machine's specific disk UUIDs, CPU, and
    # detected hardware.
    #
    # It is machine-specific generated output, but Nix flakes require everything
    # they reference to be tracked by git (or at least present in the git tree —
    # it doesn't have to be committed).
    #
    # NixOS generates hardware-configuration.nix into /etc/nixos/ by default
    # during install. Referencing it by absolute path means it never needs to be
    # in the repo at all. The trade-off is the flake is no longer fully
    # self-contained — the file is needed present on the machine.
    #
    # However,since it contains nothing sensitive — just filesystem UUIDs,
    # kernel modules, and hardware quirks. It can belong in the repo alongside
    # the config that depends on it. Keeping everything self contained.
    # ──────────────────────────────────────────────────────────────────────────
    ./hardware-configuration.nix
    ./profile.nix
    ../../src/system
  ];

  # ────────────────────────────────────────────────────────────────────────────
  # SYSTEM STATE VERSION
  # ────────────────────────────────────────────────────────────────────────────
  # Like home.stateVersion in gnome.nix, this is set once at install time and
  # never changed. It tells NixOS which release the system config was written
  # against. It does NOT control which package versions you get — that's
  # determined by your flake inputs (the nixpkgs pin in flake.lock).
  # ────────────────────────────────────────────────────────────────────────────
  system.stateVersion = stateVersion;
}
