# ──────────────────────────────────────────────────────────────────────────────
# src/pkgs/editor/vscode/extensions/lang/arduino.nix
# ──────────────────────────────────────────────────────────────────────────────

{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.cypher-os.pkgs.dev.ide.gui.vscode;
  vscMkt = pkgs.nix-vscode-extensions.vscode-marketplace;
  #openVsx = pkgs.nix-vscode-extensions.open-vsx;
in
{
  imports = [ ../../options.nix ];

  config = lib.mkIf (cfg.enable && cfg.extensions.lang.arduino.enable) {
    programs.vscode.extensions =
      with pkgs.vscode-extensions;
      [
        # ──────────────────────────────────────────────────────────────────────
        # Tier 1: extensions available as pkgs.vscode-extensions.*
        # ──────────────────────────────────────────────────────────────────────
      ]
      ++ [
        # ──────────────────────────────────────────────────────────────────────
        # Tier 2: nix-vscode-extensions (marketplace/open-vsx).
        # ──────────────────────────────────────────────────────────────────────
        # ──────────────────────────────────────────────────────────────────────
        # Arduino Community Edition — the maintained successor to the
        # deprecated Microsoft arduino extension
        # (ms-vscode.vscode-arduino).
        #
        # The Microsoft extension does not support arduino-cli or Arduino
        # IDE 2.x properly.
        #
        # This extension delegates all compile/upload work to arduino-cli
        # (in PATH) so it does not require vscode.fhs.
        #
        # If the serial monitor bridge fails with a dynamic linker error
        # at runtime, switch package to pkgs.vscode.fhs (one-line change —
        # all other config carries over unchanged).
        #
        # Microsoft's original extension (ms-vscode.vscode-arduino) was
        # removed from the marketplace on October 1, 2024 and the
        # repository archived.
        #
        # The community-maintained fork lives under the vscode-arduino
        # GitHub organisation, hence the publisher name matching the org
        # ──────────────────────────────────────────────────────────────────────
        vscMkt.vscode-arduino.vscode-arduino-community
      ];

    # ──────────────────────────────────────────────────────────────────────────
    # userSettings: written to VSCode's settings.
    # ──────────────────────────────────────────────────────────────────────────
    cypher-os.pkgs.dev.ide.gui.vscode._sharedSettings = {
      # ────────────────────────────────────────────────────────────────────────
      # arduino-cli is the compile/upload backend. The extension resolves it
      # from $PATH — no absolute path needed since arduino-cli is a statically-
      # linked Go binary (no FHS chroot required unlike native .node addons).
      # useArduinoCli must be true — the legacy IDE 1.x builder is not present.
      # Per-workspace board/port settings live in .vscode/arduino.json (auto-
      # generated by the extension on first sketch open — safe to commit).
      # ────────────────────────────────────────────────────────────────────────
      "arduino.useArduinoCli" = true;
      "arduino.commandPath" = "arduino-cli";
      "arduino.logLevel" = "info";
      "arduino.clearOutputOnBuild" = true;
      "arduino.defaultBaudRate" = 9600;
    };
  };
}
